### ISSUE TITLE
`npm install` fails because of dependency on event-stream@3.3.6 (which npm security yanked last week)

### ISSUE THREAD

**Issue by jeremyBanks** [urbit/urbit-wallet-generator#4]
```
$ npm install
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@3.3.6
````

see https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

**Comment by vvisigoth** [comment]
Whoa. Thanks for catching this! Taking a look now...

**Comment by vvisigoth** [comment]
It appears that the attack is targeted to the developers and users of Copay. Bad for them, good for us.

> The event-stream package is widely used, but the malicious code targeted developers at a company that had a very specific development environment setup: running the payload in any other environment has no effect. This specific targeting means that, ultimately, most developers would not be affected even if they had mistakenly installed the malicious module.

> The injected code targets the Copay application. When a developer at Copay runs one of their release build scripts, the resulting code is modified before being bundled into the application. The code was designed to harvest account details and private keys from accounts having a balance of more than 100 Bitcoin or 1000 Bitcoin Cash.

We'll rebuild and re-release with the version of event-stream being maintained by npm. cc @jtobin
