### ISSUE TITLE
Add the ability to manually enter a ship name in order to generate a wallet without urbit-ships.txt

### ISSUE THREAD

**Issue by msutherl** [urbit/urbit-wallet-generator#6]
Users interested in generating an urbit wallet for a ship known could (I think) use wallet generator today if we added the ability to input a ship name manually at step 2 of 7 rather than needing urbit-ships.txt (a file of unknown format to the user).

**Comment by Fang-** [comment]
Pretty sure this is on our list for Bridge + Wallet Generator integration. Soon! (:

**Comment by msutherl** [comment]
@Fang- ok, cool!

**Comment by jtobin** [comment]
Closing per #14.
